/**
 * LLM gateway client — calls the LiteLLM proxy (OpenAI-compatible API).
 * Falls back to a deterministic stub response when the gateway is unavailable.
 */

export interface LlmMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface LlmResponse {
  content: string;
  model: string;
  tokenUsage: { prompt: number; completion: number; total: number };
}

export interface LlmConfig {
  gatewayUrl: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
}

const DEFAULT_MODEL = 'gpt-4o';

export class LlmService {
  private readonly gatewayUrl: string;
  private readonly defaultModel: string;

  constructor(config: LlmConfig) {
    this.gatewayUrl = config.gatewayUrl;
    this.defaultModel = config.model ?? DEFAULT_MODEL;
  }

  async chat(
    messages: LlmMessage[],
    options?: { model?: string; temperature?: number; maxTokens?: number },
  ): Promise<LlmResponse> {
    const model = options?.model ?? this.defaultModel;

    try {
      const response = await fetch(`${this.gatewayUrl}/chat/completions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model,
          messages,
          temperature: options?.temperature ?? 0.2,
          max_tokens: options?.maxTokens ?? 4096,
        }),
      });

      if (!response.ok) {
        throw new Error(`LLM gateway error: ${response.status} ${response.statusText}`);
      }

      const data = (await response.json()) as {
        choices: Array<{ message: { content: string } }>;
        model: string;
        usage: { prompt_tokens: number; completion_tokens: number; total_tokens: number };
      };

      return {
        content: data.choices[0].message.content,
        model: data.model,
        tokenUsage: {
          prompt: data.usage.prompt_tokens,
          completion: data.usage.completion_tokens,
          total: data.usage.total_tokens,
        },
      };
    } catch {
      // Fallback for dev/testing when no LLM gateway is available
      return this.fallbackResponse(messages, model);
    }
  }

  /**
   * Deterministic fallback that generates a basic test structure
   * when the LLM gateway is unavailable.
   */
  private fallbackResponse(messages: LlmMessage[], model: string): LlmResponse {
    const userMessage = messages.find((m) => m.role === 'user')?.content ?? '';

    // Extract basic info from the user prompt to generate reasonable output
    const requirementMatch = userMessage.match(/Requirement:\s*(.+?)(?:\n|$)/i);
    const requirementTitle = requirementMatch?.[1]?.trim() ?? 'Untitled Requirement';

    const content = `import { test, expect } from '@playwright/test';

// @generated — AI-generated test (LLM gateway unavailable, using fallback)
// @covers ${requirementTitle}

test.describe('${requirementTitle}', () => {
  test('should satisfy the requirement', async ({ page }) => {
    // TODO: Implement test steps based on acceptance criteria
    // This is a placeholder generated by the deterministic fallback.
    // Connect the LLM gateway for full AI generation.
    await page.goto('/');
    await expect(page).toHaveTitle(/.+/);
  });
});
`;

    return {
      content,
      model: `${model}-fallback`,
      tokenUsage: { prompt: 0, completion: 0, total: 0 },
    };
  }
}
